version: '3.4'

services:
  myapp:
    image: myapp
    build:
      context: app
      dockerfile: ./Dockerfile
    links: 
      - "mysshserver"

  mysshserver:
    image: mysshserver
    build:
      context: ssh
      dockerfile: ./Dockerfile