version: '3.4'

services:

  mysshserver:
    image: mysshserver
    build:
      dockerfile: ssh/Dockerfile

  myapp:
    image: myapp
    build:
      dockerfile: app/Dockerfile
    depends_on:
      - mysshserver
